version: "{build}"

platform: x64

clone_folder: c:\gopath\src\github.com\tuxagon\yata-cli

environment:
  GOPATH: c:\gopath
  matrix:
    - environment:
      GOVERSION: 1.8

init:
  - git config --global core.autocrlf input

install:
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.msi
  - msiexec /i go%GOVERSION%.windows-amd64.msi /q
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env

build: false
deploy: false

test_script:
  - go build github.com/tuxagon/yata-cli
  - for /f "" %%G in ('go list github.com/tuxagon/yata-cli/... ^| find /i /v "/vendor/"') do ( go test %%G & IF ERRORLEVEL == 1 EXIT 1)